SELECT PRODUCT_CODE, (PRICE * SUM(SALES_AMOUNT)) as SALES
FROM PRODUCT as P
LEFT JOIN OFFLINE_SALE as O
ON P.PRODUCT_ID = O.PRODUCT_ID 
GROUP BY P.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC ;